# -*- coding: utf-8 -*-
"""emotion detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-XX-B1DfcIA_6IaKTSdn_c4c7REfxfV
"""

# load the dataset
from datasets import load_dataset

data=load_dataset('dair-ai/emotion')

print(data) # print the data top check the split

print(data['train'][0]) # print first row of train data

# divide the columns and make them as a list
train_text=data['train']['text']
train_label=data['train']['label']

train_text=list(train_text)
train_label=list(train_label)

# print first three rows of text and labels
print(train_text[:3])
print(train_label[:3])

from transformers import AutoTokenizer

tokenizer=AutoTokenizer.from_pretrained('bert-base-uncased')

# split the test data into a list and tokenize them
test_texts = list(data['test']['text'])
test_labels = list(data['test']['label'])

test_encodings = tokenizer(
    test_texts,
    padding=True,
    truncation=True
)

# tokenize the train data
token=tokenizer(train_text,padding=True, truncation=True)
print(token[0])

print(token.keys())

import torch
from torch.utils.data import Dataset

class EmotionDataset(Dataset):

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {}
        for key in self.encodings:
          item[key] = torch.tensor(self.encodings[key][idx])
          item['labels'] = torch.tensor(self.labels[idx]) # Explicitly set dtype to torch.long
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = EmotionDataset(token, train_label)
test_dataset = EmotionDataset(test_encodings, test_labels)

from transformers import TrainingArguments, Trainer

training_args=TrainingArguments(
  output_dir='./results',
  num_train_epochs=1,
  per_device_train_batch_size=16,
  per_device_eval_batch_size=64,
  logging_dir="./logs",
  logging_steps=10
)

from transformers import AutoModelForSequenceClassification

model=AutoModelForSequenceClassification.from_pretrained('bert-base-uncased',num_labels=6)

trainer=Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset
)

trainer.train()

trainer.evaluate()

print(dir(train_dataset))

import numpy as np
from sklearn.metrics import accuracy_score

predictions = trainer.predict(test_dataset)

y_pred=np.argmax(predictions.predictions,axis=1)
y_true=predictions.label_ids

accuracy=accuracy_score(y_true,y_pred)
print(f"Accuracy: {accuracy}")

from sklearn.metrics import classification_report

print(classification_report(y_true, y_pred))

text = "I am feeling very happy today"

tokens=tokenizer(
    text,
    return_tensors='pt',
    padding=True,
    truncation=True
)

# Move tokens to the same device as the model
tokens = {key: val.to(model.device) for key, val in tokens.items()}

outputs=model(**tokens)

predict=torch.argmax(outputs.logits,dim=1)

print(predict.item())

print(model.config.id2label[predict.item()])

id2label = {
    0: "sadness",
    1: "joy",
    2: "love",
    3: "anger",
    4: "fear",
    5: "surprise"
}

label2id = {v: k for k, v in id2label.items()}

model.config.id2label = id2label
model.config.label2id = label2id

model.save_pretrained("emotion_model")
tokenizer.save_pretrained("emotion_model")

import os

print(os.listdir("emotion_model"))

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained("emotion_model")

print(model.config.id2label)
print(model.config.label2id)

!ls emotion_model

